In [ ]:
print("Hello pratham")

Hello pratham


In [ ]:
import torch


In [ ]:
print(torch.__version__)

2.6.0+cu124



## Creating Tensors :




In [ ]:
a = torch.empty(2,3)

In [ ]:
type(a)

torch.Tensor

In [ ]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.rand(2,3)

tensor([[0.4833, 0.3167, 0.4782],
        [0.1635, 0.6353, 0.3886]])

In [ ]:
torch.randint(2,8,(2,3))

tensor([[5, 4, 6],
        [3, 4, 7]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
torch.eye(5) #For creating Identity matrix

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

## Tensor Shapes :

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
## Method for creating same shapes tensors from given shape
torch.empty_like(x) # values diff but same shape as given

tensor([[135147721825664, 135147721825664,              32],
        [            112,          264784,              60]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
x.dtype

torch.int64

## Tensor Data Types

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
# Changing dtypes
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
 # We use majorly float32 for Deep learning tasks

In [ ]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Mathematical Operations

In [ ]:
x = torch.rand(2,3)
x

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

In [ ]:
x + 2

tensor([[2.2239, 2.3023, 2.1784],
        [2.8238, 2.5557, 2.9770]])

In [ ]:
# int divison
a = (x*100)//3

In [ ]:
# mod
a%2



tensor([[1., 0., 1.],
        [1., 0., 0.]])

## Element wise operations

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)

tensor([[0.9051, 0.5989, 0.4450],
        [0.7278, 0.4563, 0.3389]])
tensor([[0.6211, 0.5530, 0.6896],
        [0.3687, 0.9053, 0.8356]])


In [ ]:
# a+b,a-b,a*b,a/b,

In [ ]:
#Power
a**b

tensor([[0.9399, 0.7531, 0.5722],
        [0.8895, 0.4915, 0.4049]])

In [ ]:
c = torch.tensor(([-2,4,2],[-3,3,-5]))

In [ ]:
torch.abs(c)

tensor([[2, 4, 2],
        [3, 3, 5]])

In [ ]:
# Round
torch.round(b)

tensor([[1., 1., 1.],
        [0., 1., 1.]])

In [ ]:
# clamp
x = torch.tensor([1,2,3,5.4,3.2,1.9])
torch.clamp(x,2,3)

tensor([2., 2., 3., 3., 3., 2.])

## Reduction Operations

In [ ]:
e = torch.randint(size=(2,3),low=2,high=9)
e

tensor([[4, 5, 4],
        [2, 7, 3]])

In [ ]:
torch.sum(e)

tensor(25)

In [ ]:
torch.sum(e,dim=0) # Along columns

tensor([ 6, 12,  7])

In [ ]:
torch.sum(e,dim=1)

tensor([13, 12])

In [ ]:
torch.median(e) #Similarly you can do mean as well

tensor(4)

In [ ]:
torch.prod(e)

tensor(3360)

In [ ]:
# Std deviation
a = e.to(dtype=torch.float32)
torch.std(a)


tensor(1.7224)

In [ ]:
# Variance
torch.var(a)

tensor(2.9667)

In [ ]:
print(a)
torch.argmax(a)

tensor([[4., 5., 4.],
        [2., 7., 3.]])


tensor(4)

## Matrix operations

In [ ]:
a = torch.tensor(([2,3,4],[7,8,9],[2,1,0]))
b = torch.tensor(([2,0,5],[9,1,6],[10,6,4]))

vector1 = torch.tensor([1,2,3])
vector2 = torch.tensor([4,5,6])



In [ ]:
torch.matmul(a,b)

tensor([[ 71,  27,  44],
        [176,  62, 119],
        [ 13,   1,  16]])

In [ ]:
# dotproduct
torch.dot(vector1,vector2)

tensor(32)

In [ ]:
torch.transpose(b,0,1)

tensor([[ 2,  9, 10],
        [ 0,  1,  6],
        [ 5,  6,  4]])

In [ ]:
# torch.det() Use karlena for calculating determinant values

In [ ]:
h = torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
h

tensor([[6., 2., 9.],
        [5., 0., 4.],
        [2., 7., 1.]])

In [ ]:
#For calculating inverse
torch.inverse(h)

tensor([[-0.1830,  0.3987,  0.0523],
        [ 0.0196, -0.0784,  0.1373],
        [ 0.2288, -0.2484, -0.0654]])

## Special Functions

In [ ]:
k = torch.randint(size=(3,3),low=1,high=9)

In [ ]:
torch.log(k)

tensor([[1.9459, 1.3863, 1.6094],
        [2.0794, 1.0986, 2.0794],
        [1.9459, 2.0794, 1.6094]])

In [ ]:
torch.exp(k)

tensor([[1096.6332,   54.5981,  148.4132],
        [2980.9580,   20.0855, 2980.9580],
        [1096.6332, 2980.9580,  148.4132]])

In [ ]:
#sigmoid
torch.sigmoid(k)

tensor([[0.9991, 0.9820, 0.9933],
        [0.9997, 0.9526, 0.9997],
        [0.9991, 0.9997, 0.9933]])

In [ ]:
z = k.to(dtype=torch.float32)

In [ ]:
torch.softmax(z,0)

tensor([[0.2119, 0.0179, 0.0453],
        [0.5761, 0.0066, 0.9094],
        [0.2119, 0.9756, 0.0453]])

In [ ]:
torch.relu(k)

tensor([[7, 4, 5],
        [8, 3, 8],
        [7, 8, 5]])

## Inplace operations

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)
m

tensor([[0.3206, 0.9753, 0.7582],
        [0.6688, 0.2651, 0.2336]])

In [ ]:
m.add_(n) # Adds n and stores in m only.

tensor([[1.6774, 1.5705, 0.5734],
        [1.4325, 0.9792, 0.9839]])

In [ ]:
m.relu_() # m karke relu in m only

tensor([[0.3206, 0.9753, 0.7582],
        [0.6688, 0.2651, 0.2336]])

## Copying a tensor

In [ ]:
a = torch.rand(2,3)

In [ ]:
b = torch.clone(a) # To copy a tensor

In [ ]:
a
b

tensor([[0.1879, 0.5534, 0.2682],
        [0.9556, 0.9761, 0.5934]])

## Reshape tensors

In [ ]:
a = torch.ones(3,4)

In [ ]:
a.reshape(4,3) #.reshape()


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# flattten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# unsqueeze
c = torch.rand(226,226,3)
c.unsqueeze(0).shape
#Adds a dimension to the given position

torch.Size([1, 226, 226, 3])

## Pytorch and Numpy

In [ ]:
import numpy as np

In [ ]:
a = torch.tensor([1,2,3])

In [ ]:
b = a.numpy()

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c = np.array([1,2,3])

In [ ]:
torch.from_numpy(c)

tensor([1, 2, 3])