<a href="https://colab.research.google.com/github/Quartz1605/PyTorch-Learnings/blob/main/PyTorch_NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print("Hello pratham")

Hello pratham


In [5]:
print("Hello maithily")

Hello maithily


In [6]:
import torch
import torch.nn as nn
# We are going to create a 5 input, 1 output neural network.

In [7]:
class Model(nn.Module):

  def __init__(self,num_features):

    super().__init__()

    self.linear = nn.Linear(num_features,1)

    self.sigmoid = nn.Sigmoid()

  def forward(self,features):

    out = self.linear(features)

    out = self.sigmoid(out)

    return out




In [8]:
features = torch.rand((10,5)) # Creating a random dataset

#Create a model
model = Model(features.shape[1])

#call the model
model(features) ## We use this here to call the forward method,no pytorch recemmonds this way.

tensor([[0.4324],
        [0.3692],
        [0.4324],
        [0.4931],
        [0.4229],
        [0.4271],
        [0.4458],
        [0.4555],
        [0.4777],
        [0.4332]], grad_fn=<SigmoidBackward0>)

In [10]:
model.linear.weight

Parameter containing:
tensor([[-0.2925,  0.1149, -0.2338, -0.4239,  0.2424]], requires_grad=True)

In [11]:
model.linear.bias

Parameter containing:
tensor([0.0303], requires_grad=True)

In [13]:
# To visualise
!pip install torchinfo

In [14]:
from torchinfo import summary

summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## Creating one with a hidden layer.

In [21]:
class Model(nn.Module):

  def __init__(self,num_features):

    super().__init__()

    self.linear1 = nn.Linear(num_features,3)
    self.relu = nn.ReLU()

    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):

    out = self.linear1(features)
    out = self.relu(out)

    out = self.linear2(out)
    out = self.sigmoid(out)

    return out



In [22]:
model = Model(features.shape[1])

In [23]:
model(features)

tensor([[0.4968],
        [0.4920],
        [0.4693],
        [0.5052],
        [0.5052],
        [0.4932],
        [0.5052],
        [0.4853],
        [0.4959],
        [0.5052]], grad_fn=<SigmoidBackward0>)

In [24]:
model.linear1.bias

Parameter containing:
tensor([-0.4149,  0.0361, -0.3125], requires_grad=True)

In [28]:
print(model.linear1.weight)
print(model.linear2.weight)


Parameter containing:
tensor([[ 0.0860, -0.4078,  0.2444, -0.2948,  0.0128],
        [ 0.2164, -0.2802, -0.2124,  0.0238,  0.4463],
        [ 0.0646, -0.0254, -0.0304, -0.0603, -0.1974]], requires_grad=True)
Parameter containing:
tensor([[-0.4240, -0.2906, -0.5317]], requires_grad=True)


In [30]:
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## The Sequential Container

In [31]:
class Model(nn.Module):

  def __init__(self,num_features):

    super().__init__()

    self.network = nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid(),
    )

  def forward(self,features):

    out = self.network(features)

    return out






In [32]:
features = torch.rand((10,5))

In [33]:
model = Model(features.shape[1])

model(features)

tensor([[0.4481],
        [0.4435],
        [0.4481],
        [0.4481],
        [0.4481],
        [0.4481],
        [0.4481],
        [0.4481],
        [0.4477],
        [0.4481]], grad_fn=<SigmoidBackward0>)