<a href="https://colab.research.google.com/github/Quartz1605/PyTorch-Learnings/blob/main/PyTorch_NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print("Hello pratham")

Hello pratham


In [5]:
print("Hello maithily")

Hello maithily


In [6]:
import torch
import torch.nn as nn
# We are going to create a 5 input, 1 output neural network.

In [7]:
class Model(nn.Module):

  def __init__(self,num_features):

    super().__init__()

    self.linear = nn.Linear(num_features,1)

    self.sigmoid = nn.Sigmoid()

  def forward(self,features):

    out = self.linear(features)

    out = self.sigmoid(out)

    return out




In [8]:
features = torch.rand((10,5)) # Creating a random dataset

#Create a model
model = Model(features.shape[1])

#call the model
model(features) ## We use this here to call the forward method,no pytorch recemmonds this way.

tensor([[0.4324],
        [0.3692],
        [0.4324],
        [0.4931],
        [0.4229],
        [0.4271],
        [0.4458],
        [0.4555],
        [0.4777],
        [0.4332]], grad_fn=<SigmoidBackward0>)

In [90]:
features.dtype

torch.float32

In [10]:
model.linear.weight

Parameter containing:
tensor([[-0.2925,  0.1149, -0.2338, -0.4239,  0.2424]], requires_grad=True)

In [11]:
model.linear.bias

Parameter containing:
tensor([0.0303], requires_grad=True)

In [13]:
# To visualise
!pip install torchinfo

In [14]:
from torchinfo import summary

summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## Creating one with a hidden layer.

In [21]:
class Model(nn.Module):

  def __init__(self,num_features):

    super().__init__()

    self.linear1 = nn.Linear(num_features,3)
    self.relu = nn.ReLU()

    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):

    out = self.linear1(features)
    out = self.relu(out)

    out = self.linear2(out)
    out = self.sigmoid(out)

    return out



In [22]:
model = Model(features.shape[1])

In [23]:
model(features)

tensor([[0.4968],
        [0.4920],
        [0.4693],
        [0.5052],
        [0.5052],
        [0.4932],
        [0.5052],
        [0.4853],
        [0.4959],
        [0.5052]], grad_fn=<SigmoidBackward0>)

In [24]:
model.linear1.bias

Parameter containing:
tensor([-0.4149,  0.0361, -0.3125], requires_grad=True)

In [28]:
print(model.linear1.weight)
print(model.linear2.weight)


Parameter containing:
tensor([[ 0.0860, -0.4078,  0.2444, -0.2948,  0.0128],
        [ 0.2164, -0.2802, -0.2124,  0.0238,  0.4463],
        [ 0.0646, -0.0254, -0.0304, -0.0603, -0.1974]], requires_grad=True)
Parameter containing:
tensor([[-0.4240, -0.2906, -0.5317]], requires_grad=True)


In [30]:
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## The Sequential Container

In [31]:
class Model(nn.Module):

  def __init__(self,num_features):

    super().__init__()

    self.network = nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid(),
    )

  def forward(self,features):

    out = self.network(features)

    return out






In [32]:
features = torch.rand((10,5))

In [33]:
model = Model(features.shape[1])

model(features)

tensor([[0.4481],
        [0.4435],
        [0.4481],
        [0.4481],
        [0.4481],
        [0.4481],
        [0.4481],
        [0.4481],
        [0.4477],
        [0.4481]], grad_fn=<SigmoidBackward0>)

## Redoing the pipline assignment using NN module

In [34]:
import pandas as pd


In [35]:
data_1 = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
data_1.head(10)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   
5    843786         M        12.45         15.70           82.57      477.1   
6    844359         M        18.25         19.98          119.60     1040.0   
7  84458202         M        13.71         20.83           90.20      577.9   
8    844981         M        13.00         21.82           87.50      519.8   
9  84501001         M        12.46         24.04           83.97      475.9   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760         0.30010              0.14710   
1          0.08474           0.07864         0.08690              0.07017   
2          0.10960           0.15990         0.19740              0.12790   
3          0.14250           0.28390         0.24140              0.10520   
4          0.10030           0.13280         0.19800              0.10430   
5          0.12780           0.17000         0.15780              0.08089   
6          0.09463           0.10900         0.11270              0.07400   
7          0.11890           0.16450         0.09366              0.05985   
8          0.12730           0.19320         0.18590              0.09353   
9          0.11860           0.23960         0.22730              0.08543   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   
5  ...          23.75           103.40       741.6            0.1791   
6  ...          27.66           153.20      1606.0            0.1442   
7  ...          28.14           110.60       897.0            0.1654   
8  ...          30.73           106.20       739.3            0.1703   
9  ...          40.68            97.65       711.4            0.1853   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   
5             0.5249           0.5355                0.1741          0.3985   
6             0.2576           0.3784                0.1932          0.3063   
7             0.3682           0.2678                0.1556          0.3196   
8             0.5401           0.5390                0.2060          0.4378   
9             1.0580           1.1050                0.2210          0.4366   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  
5                  0.12440          NaN  
6                  0.08368          NaN  
7                  0.11510          NaN  
8                  0.10720          NaN  
9                  0.20750          NaN  

[10 rows x 33 columns]

In [36]:
data_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [48]:
data_1.drop(columns=["id","Unnamed: 32"],inplace=True)

In [51]:
data_1.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [55]:
X = data_1.iloc[:,1:]
y = data_1.iloc[:,0]

In [58]:
y

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [59]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [61]:
from sklearn.preprocessing import LabelEncoder,StandardScaler

y_train = LabelEncoder().fit_transform(y_train)


In [63]:
y_train.shape

(455,)

In [64]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

In [69]:
type(X_train)

numpy.ndarray

In [70]:
# Converting array to tensor
X_train = torch.from_numpy(X_train)
y_train = torch.from_numpy(y_train)

In [72]:
X_train.shape

torch.Size([455, 30])

In [102]:
X_train = X_train.to(torch.float32) ## This step very important as model accepts things which are float32 in nn Module.

In [98]:
X_train.dtype

torch.float32

In [99]:
class MySimpleNN(nn.Module):

  def __init__(self,num_features):
    super().__init__()

    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()


  def forward(self,features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out


  def loss_function(self,y_pred,y):

    epsilon = 1e-7
    y_pred = torch.clamp(y_pred,epsilon,1-epsilon)

    loss = -(y*torch.log(y_pred) + (1-y)*torch.log(1-y_pred)).mean()
    return loss

In [127]:
learning_rate = 0.1
epochs = 25

In [112]:
model = MySimpleNN(X_train.shape[1])

for epoch in range(epochs):

  output = model(X_train)

  loss = model.loss_function(output,y_train)

  loss.backward()

  with torch.no_grad():

    model.linear.weight -= learning_rate*model.linear.weight.grad
    model.linear.bias -= learning_rate*model.linear.bias.grad

  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()


  print(f"Epoch {epoch} and loss is {loss}")


Epoch 0 and loss is 0.7302328944206238
Epoch 1 and loss is 0.7178259491920471
Epoch 2 and loss is 0.7102476954460144
Epoch 3 and loss is 0.7053318023681641
Epoch 4 and loss is 0.7018622159957886
Epoch 5 and loss is 0.699195146560669
Epoch 6 and loss is 0.696997880935669
Epoch 7 and loss is 0.6950991153717041
Epoch 8 and loss is 0.693408191204071
Epoch 9 and loss is 0.6918748021125793
Epoch 10 and loss is 0.6904688477516174
Epoch 11 and loss is 0.6891708970069885
Epoch 12 and loss is 0.6879669427871704
Epoch 13 and loss is 0.6868463158607483
Epoch 14 and loss is 0.6858003735542297
Epoch 15 and loss is 0.6848223209381104
Epoch 16 and loss is 0.6839056015014648
Epoch 17 and loss is 0.6830452084541321
Epoch 18 and loss is 0.6822363138198853
Epoch 19 and loss is 0.6814747452735901
Epoch 20 and loss is 0.6807571649551392
Epoch 21 and loss is 0.680079996585846
Epoch 22 and loss is 0.6794403791427612
Epoch 23 and loss is 0.6788356900215149
Epoch 24 and loss is 0.6782636642456055
Epoch 25 and l

In [113]:
model.linear.weight

Parameter containing:
tensor([[ 0.0046,  0.0269,  0.1642, -0.1288,  0.0355, -0.0546,  0.0675, -0.1157,
          0.0158,  0.0604,  0.0640,  0.0361, -0.0912, -0.0187, -0.0783,  0.0440,
          0.1144, -0.0832,  0.0493, -0.0658, -0.0280, -0.0537, -0.0984,  0.2035,
          0.0873,  0.1169, -0.0421, -0.0219, -0.0868, -0.0973]],
       requires_grad=True)

In [ ]:
y_pred

In [118]:
from sklearn.metrics import confusion_matrix,accuracy_score
with torch.no_grad():
  y_pred = model(X_train)
  y_pred = (y_pred>).float()

accuracy_score(y_pred,y_train)


0.6175824175824176

## Loss function from pyTorch

In [123]:
class MySimpleNN(nn.Module):

  def __init__(self,num_features):
    super().__init__()

    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()


  def forward(self,features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out



In [124]:
loss_function = nn.BCELoss()

In [125]:
model = MySimpleNN(X_train.shape[1])

for epoch in range(epochs):

  output = model(X_train)

  loss = loss_function(output,(y_train.to(torch.float32)).reshape(455,1))

  loss.backward()

  with torch.no_grad():

    model.linear.weight -= learning_rate*model.linear.weight.grad
    model.linear.bias -= learning_rate*model.linear.bias.grad

  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()


  print(f"Epoch {epoch} and loss is {loss}")

Epoch 0 and loss is 0.7710312604904175
Epoch 1 and loss is 0.5558180809020996
Epoch 2 and loss is 0.448384165763855
Epoch 3 and loss is 0.38614416122436523
Epoch 4 and loss is 0.3448607921600342
Epoch 5 and loss is 0.3150676488876343
Epoch 6 and loss is 0.2923276722431183
Epoch 7 and loss is 0.27426600456237793
Epoch 8 and loss is 0.259487509727478
Epoch 9 and loss is 0.24711383879184723
Epoch 10 and loss is 0.2365623116493225
Epoch 11 and loss is 0.22742943465709686
Epoch 12 and loss is 0.219426229596138
Epoch 13 and loss is 0.21233971416950226
Epoch 14 and loss is 0.20600895583629608
Epoch 15 and loss is 0.20030993223190308
Epoch 16 and loss is 0.19514529407024384
Epoch 17 and loss is 0.1904374063014984
Epoch 18 and loss is 0.1861235350370407
Epoch 19 and loss is 0.18215234577655792
Epoch 20 and loss is 0.17848137021064758
Epoch 21 and loss is 0.17507508397102356
Epoch 22 and loss is 0.17190364003181458
Epoch 23 and loss is 0.16894158720970154
Epoch 24 and loss is 0.16616719961166382

## Using Optimizers


In [128]:
model = MySimpleNN(X_train.shape[1])

## model.parameters gives you a weights and biases of your model.
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)

for epoch in range(epochs):

  output = model(X_train)

  loss = loss_function(output,(y_train.to(torch.float32)).reshape(455,1))

  optimizer.zero_grad()

  loss.backward()

  optimizer.step()



  print(f"Epoch {epoch} and loss is {loss}")

Epoch 0 and loss is 0.7880789041519165
Epoch 1 and loss is 0.5633254051208496
Epoch 2 and loss is 0.45141056180000305
Epoch 3 and loss is 0.3870362341403961
Epoch 4 and loss is 0.34483960270881653
Epoch 5 and loss is 0.31472280621528625
Epoch 6 and loss is 0.2919498682022095
Epoch 7 and loss is 0.2739972770214081
Epoch 8 and loss is 0.2593923807144165
Epoch 9 and loss is 0.24721568822860718
Epoch 10 and loss is 0.2368622124195099
Epoch 11 and loss is 0.2279169261455536
Epoch 12 and loss is 0.22008509933948517
Epoch 13 and loss is 0.21315133571624756
Epoch 14 and loss is 0.20695430040359497
Epoch 15 and loss is 0.20137062668800354
Epoch 16 and loss is 0.1963040977716446
Epoch 17 and loss is 0.19167855381965637
Epoch 18 and loss is 0.18743285536766052
Epoch 19 and loss is 0.18351706862449646
Epoch 20 and loss is 0.17989026010036469
Epoch 21 and loss is 0.1765182763338089
Epoch 22 and loss is 0.17337246239185333
Epoch 23 and loss is 0.17042846977710724
Epoch 24 and loss is 0.1676655858755