<a href="https://colab.research.google.com/github/Quartz1605/PyTorch-Learnings/blob/main/PyTorch_DatasetLoader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello pratham")

Hello pratham


In [5]:
import torch
from sklearn.datasets import make_classification

In [7]:
## Creating fake data for testing
X,y = make_classification(
    n_samples=10,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

In [10]:
X.shape

(10, 2)

In [11]:
X = torch.from_numpy(X)
y = torch.from_numpy(y)

In [13]:
X = X.to(torch.float32)

In [14]:
X.dtype

torch.float32

In [15]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [16]:
y = y.to(torch.long)

## Beginning the dataset Batch work

In [18]:
from torch.utils.data import Dataset,DataLoader


In [19]:
# To basically make a Dataset ready for DataLoader which splits it into batches.
# Yeh magic methods hai and name and all sab same rahega/Rakhna.
# Yeh code ko same hi rakhna always, don't change kabhi.
class CustomDataset(Dataset):

  def __init__(self,features,labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self,index):
    return self.features[index],self.labels[index]

In [20]:
dataset = CustomDataset(X,y)

In [21]:
len(dataset)

10

In [22]:
dataset[0]

(tensor([ 1.0683, -0.9701]), tensor(1))

In [23]:
dataloader = DataLoader(dataset,batch_size=2,shuffle=True)
# Batch size tells you kitne rows chahiye.

In [24]:
for batch_features,batch_label in dataloader:
  print(batch_features)
  print(batch_label)
  print("-"*50)

tensor([[-0.7206, -0.9606],
        [-1.9629, -0.9923]])
tensor([0, 0])
--------------------------------------------------
tensor([[-0.9382, -0.5430],
        [ 1.8997,  0.8344]])
tensor([1, 1])
--------------------------------------------------
tensor([[ 1.7774,  1.5116],
        [-0.5872, -1.9717]])
tensor([1, 0])
--------------------------------------------------
tensor([[ 1.7273, -1.1858],
        [-1.1402, -0.8388]])
tensor([1, 0])
--------------------------------------------------
tensor([[-2.8954,  1.9769],
        [ 1.0683, -0.9701]])
tensor([0, 1])
--------------------------------------------------


## Improving the current code using Mini Batch Gradient Descent

In [32]:
## This is for my own revision
import torch.nn as nn


class Model(nn.Module):

  def __init__(self,num_features):

    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out



In [31]:
X.shape

torch.Size([10, 2])

In [38]:
batch_label

tensor([ 1.0683, -0.9701])

In [41]:
model = Model(X.shape[1])

epochs = 25
learning_rate = 0.1

loss = nn.BCELoss()

optimizer = torch.optim.SGD(model.parameters(),learning_rate)


for epoch in range(epochs):

  for batch_features,batch_label in dataloader:

     outputs = model(batch_features)

     loss_val = loss(outputs,(batch_label.to(torch.float32)).reshape(2,1))

     optimizer.zero_grad()

     loss_val.backward()

     optimizer.step()

     optimizer.zero_grad()








In [49]:
model = Model(X.shape[1])

model.eval() ## Set the model to a evaluation mode.

with torch.no_grad():
  y_pred = model(X)

y_pred = ((y_pred>0.5).int())

# from sklearn.metrics import accuracy_score
# accuracy_score(y_pred,y)

y_pred.reshape(1,10)


tensor([[1, 0, 0, 0, 0, 0, 1, 1, 1, 0]], dtype=torch.int32)

In [46]:
y

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])